version: "2"

services:
    hslmapservice:
        container_name: hsl-map-server
        build:
            context: .
            dockerfile: .docker/docker-hsl-mapserver.dockerfile
        links:
          - hslrouterest:hslrouterest
        ports:
          - "3000:3000"
        volumes:
          - .:/var/www/hslmapserver
        working_dir: /var/www/hslmapserver
        env_file:
          - ./.docker/env/app.${APP_ENV}.env
        networks:
          - homework-network
       
    hslrouterest:
        container_name: hsl-route-rest
        build:
            context: .
            dockerfile: .docker/docker-hsl-routerest.dockerfile
        links:
          - hslmongodb:hslmongodb
        ports:
          - "3030:3030"
        volumes:
          - .:/var/www/hslrouterest
        working_dir: /var/www/hslrouterest
        env_file:
          - ./.docker/env/app.${APP_ENV}.env
        networks:
          - homework-network
          
    hslmongodb:
        container_name: hsl-mongodb
        build:
            context: .
            dockerfile: .docker/docker-hsl-mongodb.dockerfile
        ports:
          - "27017:27017"
        env_file:
          - ./.docker/env/app.${APP_ENV}.env
        networks:
          - homework-network

networks:
    homework-network:
      driver: bridge